---
# defaults file for db


ansible_python_interpreter: /usr/bin/python3
base_python_package: "{{ ansible_python_interpreter | default('/usr/bin/python3') | basename }}"

db_name: enterprise
db_user: enterprise
db_password: "@Mesika70"
update_apt_cache: yes