---
# tasks file for web

- ansible.builtin.import_tasks: setup_git_repo.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_virtualenv.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_django_app.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_uwsgi.yml
  tags: deploy
